# Generated by Django 5.1.1 on 2024-09-07 04:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
