"""
Django settings for CurdWithClassBase project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4^^5yec4jrm1#nan%_!$0vdkkytr$u2iou=q4co^q6hajt!5f9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'tinymce'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'CurdWithClassBase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CurdWithClassBase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# TINYMCE_DEFAULT_CONFIG = {
#     'theme': 'silver',
#     'plugins': 'link image preview codesample fullscreen',
#     'toolbar': 'undo redo | bold italic | alignleft aligncenter alignright | code',
#     'height': 400,
#     'width': '100%',
# }

# TINYMCE_JS_URL = 'http://debug.example.org/tiny_mce/tiny_mce_src.js'
# TINYMCE_JS_URL = 'http://debug.example.org/tiny_mce/tiny_mce_src.js'
# TINYMCE_JS_URL = os.path.join(STATIC_URL, "path/to/tiny_mce/tiny_mce.js")
# TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/no-api-key/tinymce/6/tinymce.min.js'
# TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/no-api-key/tinymce/7/tinymce.min.js'
# TINYMCE_COMPRESSOR = False

TINYMCE_DEFAULT_CONFIG = {
    "height": "320px",
    "width": "960px",
    "menubar": True,
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
    "fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "language": "es_ES",  # To force a specific language instead of the Django current language.
}

# TINYMCE_DEFAULT_CONFIG = {
#     'height': 360,
#     'width': 800,
#     'plugins': "link image preview codesample",
#     'toolbar': "undo redo | bold italic | alignleft aligncenter alignright | code",
#     'menubar': False,
#     'statusbar': True,
# }

# TINYMCE_DEFAULT_CONFIG = {
#     'height': 500,
#     'width': 800,
#     'plugins': "advlist autolink lists link image charmap print preview anchor",
#     'toolbar': "undo redo | formatselect | bold italic backcolor | \
#                 alignleft aligncenter alignright alignjustify | \
#                 bullist numlist outdent indent | removeformat | help",
#     'menubar': False,
#     'statusbar': True,
# }

# TINYMCE_DEFAULT_CONFIG = {
#     'height': 500,
#     'plugins': "advlist autolink lists link image charmap print preview anchor",
#     'toolbar': "undo redo | formatselect | bold italic backcolor | "
#                "alignleft aligncenter alignright alignjustify | "
#                "bullist numlist outdent indent | removeformat | help",
#     'menubar': False,
#     'statusbar': True,
#     'content_style': 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
#     'api_key': '3ak0waq8prlrcev91wwqm9isbgqq6enckal57wixp55hd386',
# }

# TINYMCE_DEFAULT_CONFIG = {
#     'height': 500,
#     'plugins': "advlist autolink lists link image charmap print preview anchor",
#     'toolbar': "undo redo | formatselect | bold italic backcolor | "
#                "alignleft aligncenter alignright alignjustify | "
#                "bullist numlist outdent indent | removeformat | help",
#     'menubar': False,
#     'statusbar': True,
#     'content_style': 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
    # 'api_key': '3ak0waq8prlrcev91wwqm9isbgqq6enckal57wixp55hd386',  # Add your TinyMCE API key here
# }


